## Import Library

In [1]:
import numpy as np

## Array

In [77]:
# numpy array
a = [1,2,3,4]
np.array(a)

array([1, 2, 3, 4])

In [79]:
#type
b = np.array([1,2,3,4])
b.dtype

dtype('int64')

In [80]:
c = np.array([[1,2,3],
              [4,5,6]])
type(c)

numpy.ndarray

In [81]:
#Shape
c.shape

(2, 3)

In [82]:
# dimensions of array
c.ndim

2

In [83]:
# size 
c.size

6

## Zero, Ones and Full

In [84]:
# Zeros(row, column)
zr = np.zeros([2,3])
zr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [87]:
on = np.ones([3,2])
on

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
# Type 
on.dtype

dtype('float64')

In [94]:
# Change type
on = np.ones([3,2], dtype=int)
on.dtype

dtype('int64')

In [88]:
np.full([2,2], 113)

array([[113, 113],
       [113, 113]])

## Random

In [13]:
# seed() to fix random
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [250]:
# normal
np.random.normal(1,10,[3,4])

array([[  6.91242806,  -6.82775504,  -3.44232827,  -2.45186158],
       [ -7.81800549,  -3.42653242,  -4.40916298, -12.23227369],
       [ -0.12798921,  10.07345943,   9.15269908,   3.29097948]])

In [251]:
# randint
np.random.randint(1,5,[4,5])

array([[4, 2, 2, 4, 3],
       [4, 4, 3, 3, 4],
       [1, 3, 4, 2, 1],
       [2, 3, 1, 4, 1]])

In [252]:
# rand
np.random.rand(3,3)

array([[0.95894927, 0.65279032, 0.63505887],
       [0.99529957, 0.58185033, 0.41436859],
       [0.4746975 , 0.6235101 , 0.33800761]])

In [254]:
# randn
np.random.randn(2,2)

array([[-0.68658948,  0.01487332],
       [-0.3756659 , -0.03822364]])

## Indexing and Slicing

In [191]:
x1 = np.arange(1,101).reshape(10,10)
x1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [199]:
# get raw 
x1[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [198]:
# get raw and column
x1[5,4]

55

In [195]:
x1[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [196]:
x1[5, :4]b

array([51, 52, 53, 54])

In [202]:
# return the size (in bytes)
x1.itemsize

8

In [204]:
x2 = np.random.randint(10, size=10)
x2

array([3, 7, 0, 1, 9, 9, 0, 4, 7, 3])

In [206]:
x2[0:3]

array([3, 7, 0])

In [208]:
# select all table and step is 2
x2[::2]

array([3, 0, 9, 0, 7])

## Arange

In [109]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
ar_step = np.arange(5,25, 5)
ar_step

array([ 5, 10, 15, 20])

## Linspace

In [98]:
lin = np.linspace(1,10,5)
lin

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Revel and Flatten

In [120]:
lin.ravel()

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [121]:
lin.flatten()

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Reshape

In [115]:
ar.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [116]:
ar.reshape(1,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

## Transpose

In [123]:
# with T
x = np.array([[1,2], [3,4]])
x.T

array([[1, 3],
       [2, 4]])

In [124]:
# with transpose
np.transpose(x)

array([[1, 3],
       [2, 4]])

## Concatenation

In [29]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [30]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [31]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.concatenate((grid, grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [33]:
np.concatenate((grid, grid), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Vertical and Horizontal

In [212]:
x = np.array([1,2,3])

grid = np.array([[9,8,7],
                [6,5,4]])

In [36]:
# Vertical
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [37]:
# Horizontal
y = np.array([[99],
             [99]])

np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## Split

In [213]:
x = np.array([1,2,3,11,22,3,2,1])

In [214]:
x1, x2, x3 = np.split(x, [3,5])

In [215]:
x1

array([1, 2, 3])

In [216]:
x2

array([11, 22])

In [217]:
x3

array([3, 2, 1])

In [248]:
slp = np.arange(1, 10)
slp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [249]:
np.split(slp, [4])

[array([1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

## Mathematic

In [130]:
math_1 = np.arange(3)
a

[1, 2, 3, 4]

In [131]:
math_1 + 5

array([5, 6, 7])

In [138]:
math_2 = np.ones([3,3])
math_2

array([[0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215]])

In [133]:
math_1 + math_2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [134]:
 math_1 * math_2

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

## Aggregation

In [48]:
np.array([1,2,3]).sum()

6

In [49]:
massive_array = np.random.random((1000,))

In [50]:
np.mean(massive_array)

0.5032107729588002

In [51]:
np.min(massive_array )

5.535686500857118e-05

In [52]:
np.max(massive_array )

0.9980254861986478

## Standard

In [181]:
person_height = [180, 170, 175, 165, 150]

In [183]:
# mean
np.mean(person_height)

168.0

In [184]:
# Standard
person_height = np.array(person_height)
np.std(person_height)

10.295630140987

##  Standard and Deviation

In [185]:
# Variance
np.var(person_height)

106.0

In [186]:
# Standard with formula
np.sqrt(np.var(person_height))

10.295630140987

## Max, Argmax and Min, Argmin

In [187]:
# max()
person_height.max()

180

In [188]:
a#argmax()
person_height.argmax()

0

In [148]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [155]:
# max with axis
grid.max(axis=1)

array([9, 6])

In [189]:
# min()
person_height.min()

150

In [154]:
# min with axis
grid.min(axis=0)

array([6, 5, 4])

## Sum

In [160]:
arr1 = np.arange(1, 10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
s = np.sum(arr1)
s

45

In [171]:
# sum with axis
sum_axis0 =np.sum(arr1, axis=0)
sum_axis0

array([12, 15, 18])

In [170]:
# 

array([ 6, 15, 24])

## Sort

In [57]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [58]:
np.argsort(x)

array([1, 0, 3, 2, 4])

In [59]:
np.random.seed(42)
MatA = np.random.randint(0,10 ,size =(4,6))

In [60]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [61]:
np.sort(MatA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [62]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Linear

In [63]:
A = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [64]:
B = np.array([[6,5],
             [4,3],
             [2,1]])

In [142]:
# dot()
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [143]:
# @
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

## Doc Exercise

In [66]:
import numpy as np

# Random Values 
np.random.seed(0)
sale_amounts = np.random.randint(20, size = [5,3])

In [67]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [68]:
# Insert index and column
import pandas as pd
quarterly_sales = pd.DataFrame(sale_amounts, index = ['Sugar', 'Salt', 'Cheese', 'Oil', 'Rice'],
                           columns = ['Jan', 'Junly', 'Sept'])

In [69]:
quarterly_sales

Jan  Junly  Sept
Sugar    12     15     0
Salt      3      3     7
Cheese    9     19    18
Oil       4      6    12
Rice      1      6     7

In [70]:
# Get price
prices = np.array([10, 8, 12])

In [71]:
data_price = pd.DataFrame(prices.reshape([1,3]), index = ['Price'],
                            columns = ['Jan', 'Junly', 'Sept'])

In [72]:
data_price

Jan  Junly  Sept
Price   10      8    12

In [73]:
quarterly_sales.shape, data_price.shape

((5, 3), (1, 3))

In [74]:
# doc quarterly sales with data price
total_price = quarterly_sales.dot(data_price.T)
total_price

Price
Sugar     240
Salt      138
Cheese    458
Oil       232
Rice      142

In [75]:
quarterly_sales.shape, data_price.T.shape

((5, 3), (3, 1))

In [76]:
# Add a column Total price
quarterly_sales['Total_prices'] = total_price
quarterly_sales

Jan  Junly  Sept  Total_prices
Sugar    12     15     0           240
Salt      3      3     7           138
Cheese    9     19    18           458
Oil       4      6    12           232
Rice      1      6     7           142